DROP TABLE IF EXISTS "area" CASCADE;

DROP TABLE IF EXISTS "categoria_insumo" CASCADE;

DROP TABLE IF EXISTS "categoria_producto" CASCADE;

DROP TABLE IF EXISTS "compra" CASCADE;

DROP TABLE IF EXISTS "compra_insumo" CASCADE;

DROP TABLE IF EXISTS "insumo" CASCADE;

DROP TABLE IF EXISTS "insumos_producto" CASCADE;

DROP TABLE IF EXISTS "merma" CASCADE;

DROP TABLE IF EXISTS "merma_insumo" CASCADE;

DROP TABLE IF EXISTS "movimiento_insumo" CASCADE;

DROP TABLE IF EXISTS "permiso" CASCADE;

DROP TABLE IF EXISTS "permisos_rol" CASCADE;

DROP TABLE IF EXISTS "producto" CASCADE;

DROP TABLE IF EXISTS "proveedor" CASCADE;

DROP TABLE IF EXISTS "razon_merma" CASCADE;

DROP TABLE IF EXISTS "rol" CASCADE;

DROP TABLE IF EXISTS "salida" CASCADE;

DROP TABLE IF EXISTS "salida_insumo" CASCADE;

DROP TABLE IF EXISTS "unidad_medida" CASCADE;

DROP TABLE IF EXISTS "usuario" CASCADE;